name: Update Movies Data

on:
  workflow_dispatch:
    inputs:
      run_movies:
        required: true
        default: "true"

  schedule:
    - cron: "0 12 * * *"

jobs:
  scrape-movies:
    if: github.event_name == 'schedule' || github.event.inputs.run_movies == 'true'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 lxml

      - name: Run Movies scraper
        run: |
          python movies_desicinemas.py

      - name: Commit movie data
        run: |
          git config user.name "strimio-bot"
          git config user.email "bot@strimio.app"

          git add site/movies movies || true
          git add movie || true

          git commit -m "Update Bollywood movies data" || echo "No changes"
          git push
